apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoreinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scoreinfo
  template:
    metadata:
      labels:
        app: scoreinfo
    spec:
      containers:
        - name: scoreinfo
          image: "scoreinfo-application:latest"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: scoreinfo-service
spec:
  selector:
    app: scoreinfo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
